version: "2"
services:
  wiitifydb:
    image: mongo:6.0
    container_name: wiitifydb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - api-network
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: api
    depends_on:
      - wiitifydb
    env_file:
      - .env
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@wiitifydb:27017
    ports:
      - "5000:5000"
    networks:
      - api-network
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
      - file-uploads:/app/public/uploads

networks:
  api-network:

volumes:
  mongo-data:
  node-modules:
  file-uploads:
